pre_noun_words = [
'der', 'die', 'das', 'den', 'dem', 'denen', 'des',
'dieser', 'diese', 'dieses', 'diesem', 'diesen',
'dessen', 'deren', 'wessen',
'ein', 'eine', 'einen', 'einem', 'einer', 'eines',
'kein', 'keine', 'keines', 'keinem', 'keinen', 'keiner',
'mein', 'meine', 'meines', 'meinem', 'meinen', 'meiner',
'dein', 'deine', 'deines', 'deinem', 'deinen', 'deiner',
'sein', 'seine', 'seines', 'seinem', 'seinen', 'seiner',
'ihr', 'ihre', 'ihres', 'ihrem', 'ihren', 'ihrer',
'eurer', 'eure', 'eures', 'eurem', 'euren',
'unser', 'unsere', 'unseres', 'unserem', 'unseren',
'mancher', 'manche', 'manches', 'manchen', 'manchem',
'jeder', 'jede', 'jedes', 'jeden', 'jedem',
'solcher', 'solche', 'solches', 'solchem', 'solchen',
'jener','jene','jenes','jenen', 'jenem',
'welcher', 'welche', 'welches', 'welchem', 'welchen',
'im',
'am',
'ans',
'ums',
'beim',
'ins',
'vom',
'zum',
'zur',
'aufs',
'fürs',
'übers',
'unters']
